version: "3.9"
services:
  android_build:
    image: plugfox/flutter:3.0.0-android-warmed
    volumes:
      - ../..:/app
    command: bash -c "cd /app && flutter clean && flutter pub get && flutter build apk --release --pub --shrink --target-platform android-arm64"
